/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SwSideDrawer {
    'open': boolean;
    'title': string;
  }
  interface SwSideDrawerAttributes extends StencilHTMLAttributes {
    'open'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SwSideDrawer': Components.SwSideDrawer;
  }

  interface StencilIntrinsicElements {
    'sw-side-drawer': Components.SwSideDrawerAttributes;
  }


  interface HTMLSwSideDrawerElement extends Components.SwSideDrawer, HTMLStencilElement {}
  var HTMLSwSideDrawerElement: {
    prototype: HTMLSwSideDrawerElement;
    new (): HTMLSwSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'sw-side-drawer': HTMLSwSideDrawerElement
  }

  interface ElementTagNameMap {
    'sw-side-drawer': HTMLSwSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
